"""added joins table maybe

Revision ID: 074a23a1f51b
Revises: 33e018d0bc18
Create Date: 2021-06-02 11:19:10.046597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074a23a1f51b'
down_revision = '33e018d0bc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SourceFeed',
    sa.Column('feedId', sa.Integer(), nullable=False),
    sa.Column('sourceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedId'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['sourceId'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('feedId', 'sourceId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SourceFeed')
    # ### end Alembic commands ###
