"""added url for rss feeds

Revision ID: 32057cd73a42
Revises: 28c1e518d7bc
Create Date: 2021-06-07 16:20:09.305028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32057cd73a42'
down_revision = '28c1e518d7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'url')
    # ### end Alembic commands ###
