"""added other tables

Revision ID: 33e018d0bc18
Revises: dffb30810ec7
Create Date: 2021-06-02 10:57:44.027901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e018d0bc18'
down_revision = 'dffb30810ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('sources_id', sa.Integer(), nullable=True),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sources_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sources_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sources_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    op.drop_table('articles')
    op.drop_table('sources')
    # ### end Alembic commands ###
