"""working on joins table

Revision ID: 48350879dac4
Revises: 074a23a1f51b
Create Date: 2021-06-02 11:37:52.106838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48350879dac4'
down_revision = '074a23a1f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feeds_sources_id_fkey', 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'sources_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('sources_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('feeds_sources_id_fkey', 'feeds', 'sources', ['sources_id'], ['id'])
    # ### end Alembic commands ###
