"""changed articles so they now get added when loading in. Also set up relationship with user.

Revision ID: 7b27a3415663
Revises: 32057cd73a42
Create Date: 2021-06-13 22:28:34.974552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b27a3415663'
down_revision = '32057cd73a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SavedArts',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articleId'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'articleId')
    )
    op.add_column('articles', sa.Column('published', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('summary', sa.String(length=5000), nullable=True))
    op.drop_column('articles', 'description')
    op.drop_column('articles', 'date_posted')
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    op.drop_column('articles', 'summary')
    op.drop_column('articles', 'published')
    op.drop_table('SavedArts')
    # ### end Alembic commands ###
